version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-booking-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - JWT_SECRET=${JWT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FRONTEND_URL=https://ai.zackz.net
    restart: unless-stopped
    networks:
      - ai-booking-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-booking-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=https://ai.zackz.net:3000
      - VITE_WEBSOCKET_URL=wss://ai.zackz.net:3000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ai-booking-network

networks:
  ai-booking-network:
    driver: bridge