version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-booking-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - JWT_SECRET=${JWT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3002,http://localhost:5173,https://ai.zackz.net
      - FRONTEND_URL=https://ai.zackz.net
    restart: unless-stopped
    networks:
      - ai-booking-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://ai.zackz.net:3000/api
        - VITE_WS_URL=ws://ai.zackz.net:3000
        - VITE_GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID}"
        - VITE_ENVIRONMENT=production
    container_name: ai-booking-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ai-booking-network

networks:
  ai-booking-network:
    driver: bridge