version: '3.8'

services:
  app:
    environment:
      - NODE_ENV=staging
    ports:
      - "3001:3000"
    restart: always

  # Enable Redis for staging
  redis:
    profiles: []

  # Monitoring service for staging
  monitoring:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - app_network
    profiles: []